### ISSUE TITLE
Error on return to Rat King

### ISSUE THREAD

**Issue by etoitau** [Zrp200/rkpd2#13]
After getting the amulet and returning to the Rat King. Got the dialog challenging me to a fight, then this error.

```
***** UCE HANDLER Library 
***** by Rohit Surwase 

***** DEVICE INFO 
Brand: google
Device: bluejay
Model: Pixel 6a
Manufacturer: Google
Product: bluejay
SDK: 34
Release: 14

***** APP INFO 
Version: 2.0.1
Installed On: 2023-01-18 16:27:27
Updated On: 2024-09-20 17:30:39
Current Date: 2024-10-01 18:36:13

***** ERROR LOG 
java.lang.RuntimeException: fatal error occurred while moving between floors. Seed:1133340188817 depth:0
	at com.zrp200.rkpd2.scenes.InterlevelScene.update(InterlevelScene.java:321)
	at com.watabou.noosa.Game.update(Game.java:285)
	at com.watabou.noosa.Game.step(Game.java:248)
	at com.watabou.noosa.Game.render(Game.java:178)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:505)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1573)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)
Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.util.Objects.checkIndex(Objects.java:359)
	at java.util.ArrayList.remove(ArrayList.java:511)
	at com.zrp200.rkpd2.levels.Level.createMob(Level.java:523)
	at com.zrp200.rkpd2.levels.Level.spawnMob(Level.java:796)
	at com.zrp200.rkpd2.actors.buffs.AscensionChallenge.onLevelSwitch(AscensionChallenge.java:256)
	at com.zrp200.rkpd2.Dungeon.switchLevel(Dungeon.java:526)
	at com.zrp200.rkpd2.scenes.InterlevelScene.descend(InterlevelScene.java:413)
	at com.zrp200.rkpd2.scenes.InterlevelScene.access$300(InterlevelScene.java:59)
	at com.zrp200.rkpd2.scenes.InterlevelScene$3.run(InterlevelScene.java:234)



***** END OF LOG *****
```

**Comment by Zrp200** [comment]
You'd actually be better off in https://github.com/TrashboxBobylev/Rat-King-Adventure, because I don't implement that fight.
