### ISSUE TITLE
Error crash when attacking 'eye' mob on the way back to surface after endgame

### ISSUE THREAD

**Issue by Isudor** [Zrp200/rkpd2#2]
Hopefully Evan can see this in case it's related to shattered, here's the log:

***** UCE HANDLER Library 
***** by Rohit Surwase 

***** DEVICE INFO 
Brand: Xiaomi
Device: venus
Model: M2011K2G
Manufacturer: Xiaomi
Product: venus_eea
SDK: 30
Release: 11

***** APP INFO 
Version: 0.3.1
Installed On: 2022-01-28 18:16:25
Updated On: 2022-01-28 18:16:25
Current Date: 2022-01-30 15:52:25

***** ERROR LOG 
java.lang.NullPointerException: Attempt to read from null array
	at com.zrp200.rkpd2.actors.mobs.Eye.canAttack(Eye.java:3)
	at com.zrp200.rkpd2.actors.hero.Hero.attackDelay(Hero.java:8)
	at com.zrp200.rkpd2.actors.hero.Talent$RKPD2LethalMomentumTracker.attachTo(Talent.java:6)
	at com.zrp200.rkpd2.actors.buffs.Buff.append(Buff.java:2)
	at com.zrp200.rkpd2.actors.hero.Talent$RKPD2LethalMomentumTracker.process(Talent.java:2)
	at com.zrp200.rkpd2.actors.hero.Hero.attackProc(Hero.java:1)
	at com.zrp200.rkpd2.actors.Char.attack(Char.java:35)
	at com.zrp200.rkpd2.actors.Char.attack(Char.java:2)
	at com.zrp200.rkpd2.actors.Char.attack(Char.java:1)
	at com.zrp200.rkpd2.actors.hero.Hero.onAttackComplete(Hero.java:2)
	at com.zrp200.rkpd2.sprites.CharSprite.onComplete(CharSprite.java:19)
	at com.watabou.noosa.MovieClip.updateAnimation(MovieClip.java:12)
	at com.watabou.noosa.MovieClip.update(MovieClip.java:3)
	at com.zrp200.rkpd2.sprites.CharSprite.update(CharSprite.java:4)
	at com.zrp200.rkpd2.sprites.HeroSprite.update(HeroSprite.java:2)
	at com.watabou.noosa.Group.update(Group.java:4)
	at com.watabou.noosa.Group.update(Group.java:4)
	at com.watabou.noosa.Scene.update(Scene.java:1)
	at com.zrp200.rkpd2.scenes.GameScene.update(GameScene.java:2)
	at com.watabou.noosa.Game.update(Game.java:9)
	at com.watabou.noosa.Game.step(Game.java:5)
	at com.watabou.noosa.Game.render(Game.java:15)
	at y.k.onDrawFrame(AndroidGraphics.java:40)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1577)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)

***** END OF LOG *****

**Comment by Zrp200** [comment]
huh, thanks. Will investigate.
